# Database connection settings
spring.datasource.url=jdbc:postgresql://db:5432/mydatabase?currentSchema=public
spring.datasource.username=user
spring.datasource.password=password

# Hibernate JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=public
